#! /bin/bash

rm -rf ~/rpmbuild
rpmdev-setuptree
gem build smart_proxy_openbolt.gemspec
cp smart_proxy_openbolt-0.0.1.gem ~/rpmbuild/SOURCES/
pushd /opt/foreman-packaging
gem2rpm -t gem2rpm/smart_proxy_plugin.spec.erb ~/rpmbuild/SOURCES/smart_proxy_openbolt-0.0.1.gem > ~/rpmbuild/SPECS/rubygem-smart_proxy_openbolt.spec
popd

rpmbuild -ba ~/rpmbuild/SPECS/rubygem-smart_proxy_openbolt.spec
cp ~/rpmbuild/RPMS/noarch/rubygem-smart_proxy_openbolt-0.0.1-1.el9.noarch.rpm .
